### ISSUE TITLE
Adding aws-lambda Operator throws cannot import name 'TemplateExists' from 'bentoctl.exceptions' 

### ISSUE THREAD

**Issue by abhishek-ch** [bentoml/aws-lambda-deploy#34]
While trying to add aws-lambda Operator, bentoctl throws

Setup:
`pip install --pre bentoctl`

> bentoctl, version 1.0.0a4

Starts with
> Cloning git@github.com:bentoml/aws-lambda-deploy.git

And throws

`ERROR:bentoctl.operator.operator:cannot import name 'TemplateExists' from 'bentoctl.exceptions' (/usr/local/lib/python3.8/site-packages/bentoctl/exceptions.py)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/bentoctl/operator/operator.py", line 82, in _import_module
    module = importlib.import_module(module_name)
  File "/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/folders/q2/zp1ts4yj36n_wlqb711d2y5r0000gq/T/tmp64zq0s3m/operator_config.py", line 1, in <module>
    from bentoctl_lambda.schemas import OPERATOR_SCHEMA
  File "/var/folders/q2/zp1ts4yj36n_wlqb711d2y5r0000gq/T/tmp64zq0s3m/bentoctl_lambda/__init__.py", line 1, in <module>
    from .generate import generate
  File "/var/folders/q2/zp1ts4yj36n_wlqb711d2y5r0000gq/T/tmp64zq0s3m/bentoctl_lambda/generate.py", line 4, in <module>
    from bentoctl.exceptions import TemplateExists, TemplateTypeNotDefined
ImportError: cannot import name 'TemplateExists' from 'bentoctl.exceptions' (/usr/local/lib/python3.8/site-packages/bentoctl/exceptions.py)
Error:  Failed to load module operator_config - cannot import name 'TemplateExists' from 'bentoctl.exceptions' (/usr/local/lib/python3.8/site-packages/bentoctl/exceptions.py).`

**Comment by jjmachan** [comment]
thanks for reporting the issue @abhishek-ch 🙌🏽 
This is because the bentoctl v1.0.0a4 does not have some of the latest changes from the main branch. We will be cutting out a release shortly but in the meantime, you can install the bentoctl from the main branch by running `pip install git+https://github.com/bentoml/bentoctl.git`

**Comment by jjmachan** [comment]
fixed with latest bentoctl and lambda operators
